export const movies = [
  {
    id: 1, slug: "inception",
    translations: {
      uz: { title: "Boshlanish", description: "Tush orqali sirlarni o'g'irlaydigan professional o'g'ri haqida hikoya." },
      ru: { title: "Начало", description: "История о профессиональном воре, который крадет секреты через сны." },
    },
    originalTitle: "Inception", year: 2010, duration: 148, rating: 8.8, quality: "HD", ageLimit: 13,
    genres: ["Sci-Fi", "Action", "Thriller"],
    actors: [
      { id: 1, name: "Leonardo DiCaprio", role: "Cobb", photo: "/actors/dicaprio.jpg" },
      { id: 2, name: "Joseph Gordon-Levitt", role: "Arthur", photo: "/actors/joseph.jpg" },
    ],
    director: { id: 1, name: "Christopher Nolan", photo: "/directors/nolan.jpg" },
    creator: { id: 1, name: "Christopher Nolan" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    trailer: "https://www.youtube.com/watch?v=YoHD9XEInc0",
    videoUrl: { uz: "/videos/inception-uz.mp4", ru: "/videos/inception-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 2, slug: "interstellar",
    translations: {
      uz: { title: "Yulduzlararo", description: "Insoniyatni qutqarish uchun kosmosga yo'l olgan guruh haqida hikoya." },
      ru: { title: "Интерстеллар", description: "История о космической экспедиции ради спасения человечества." },
    },
    originalTitle: "Interstellar", year: 2014, duration: 169, rating: 8.6, quality: "HD", ageLimit: 13,
    genres: ["Sci-Fi", "Drama"],
    actors: [
      { id: 3, name: "Matthew McConaughey", role: "Cooper", photo: "/actors/matthew.jpg" },
      { id: 4, name: "Anne Hathaway", role: "Brand", photo: "/actors/anne.jpg" },
    ],
    director: { id: 2, name: "Christopher Nolan", photo: "/directors/nolan.jpg" },
    creator: { id: 2, name: "Christopher Nolan" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    trailer: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    videoUrl: { uz: "/videos/interstellar-uz.mp4", ru: "/videos/interstellar-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 3, slug: "the-dark-knight",
    translations: {
      uz: { title: "Qorong'u Ritsar", description: "Batman Joker bilan yuzma-yuz keladi." },
      ru: { title: "Темный рыцарь", description: "Бэтмен сталкивается с Джокером." },
    },
    originalTitle: "The Dark Knight", year: 2008, duration: 152, rating: 9.0, quality: "HD", ageLimit: 16,
    genres: ["Action", "Crime", "Drama"],
    actors: [
      { id: 5, name: "Christian Bale", role: "Bruce Wayne", photo: "/actors/bale.jpg" },
      { id: 6, name: "Heath Ledger", role: "Joker", photo: "/actors/ledger.jpg" },
    ],
    director: { id: 3, name: "Christopher Nolan", photo: "/directors/nolan.jpg" },
    creator: { id: 3, name: "Christopher Nolan" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg",
    trailer: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    videoUrl: { uz: "/videos/darkknight-uz.mp4", ru: "/videos/darkknight-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 4, slug: "avatar",
    translations: {
      uz: { title: "Avatar", description: "Pandora sayyorasidagi jang haqida hikoya." },
      ru: { title: "Аватар", description: "История борьбы на планете Пандора." },
    },
    originalTitle: "Avatar", year: 2009, duration: 162, rating: 7.9, quality: "HD", ageLimit: 13,
    genres: ["Sci-Fi", "Adventure"], actors: [],
    director: { id: 4, name: "James Cameron", photo: "/directors/cameron.jpg" },
    creator: { id: 4, name: "James Cameron" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg",
    trailer: "https://www.youtube.com/watch?v=5PSNL1qE6VY",
    videoUrl: { uz: "/videos/avatar-uz.mp4", ru: "/videos/avatar-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 5, slug: "oppenheimer",
    translations: {
      uz: { title: "Oppengeymer", description: "Atom bombasining yaratilishi haqida." },
      ru: { title: "Оппенгеймер", description: "История создания атомной бомбы." },
    },
    originalTitle: "Oppenheimer", year: 2023, duration: 180, rating: 8.5, quality: "HD", ageLimit: 16,
    genres: ["Drama", "History"],
    actors: [
      { id: 7, name: "Cillian Murphy", role: "Oppenheimer", photo: "/actors/murphy.jpg" },
      { id: 8, name: "Emily Blunt", role: "Kitty", photo: "/actors/blunt.jpg" },
    ],
    director: { id: 5, name: "Christopher Nolan", photo: "/directors/nolan.jpg" },
    creator: { id: 5, name: "Christopher Nolan" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    trailer: "https://www.youtube.com/watch?v=uYPbbksJxIg",
    videoUrl: { uz: "/videos/oppenheimer-uz.mp4", ru: "/videos/oppenheimer-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 6, slug: "gladiator",
    translations: {
      uz: { title: "Gladiator", description: "Rim jangchisi haqida." },
      ru: { title: "Гладиатор", description: "История римского воина." },
    },
    originalTitle: "Gladiator", year: 2000, duration: 155, rating: 8.5, quality: "HD", ageLimit: 16,
    genres: ["Action", "Drama"], actors: [],
    director: { id: 6, name: "Ridley Scott", photo: "/directors/scott.jpg" },
    creator: { id: 6, name: "Ridley Scott" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg",
    trailer: "https://www.youtube.com/watch?v=owK1qxDselE",
    videoUrl: { uz: "/videos/gladiator-uz.mp4", ru: "/videos/gladiator-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 7, slug: "matrix",
    translations: {
      uz: { title: "Matrix", description: "Virtual dunyo haqidagi film." },
      ru: { title: "Матрица", description: "Фильм о виртуальной реальности." },
    },
    originalTitle: "The Matrix", year: 1999, duration: 136, rating: 8.7, quality: "HD", ageLimit: 16,
    genres: ["Sci-Fi", "Action"], actors: [],
    director: { id: 7, name: "Wachowski Sisters", photo: "/directors/wachowski.jpg" },
    creator: { id: 7, name: "Wachowski Sisters" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
    trailer: "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    videoUrl: { uz: "/videos/matrix-uz.mp4", ru: "/videos/matrix-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 8, slug: "joker",
    translations: {
      uz: { title: "Joker", description: "Psixologik drama." },
      ru: { title: "Джокер", description: "Психологическая драма." },
    },
    originalTitle: "Joker", year: 2019, duration: 122, rating: 8.4, quality: "HD", ageLimit: 18,
    genres: ["Drama", "Crime"], actors: [],
    director: { id: 8, name: "Todd Phillips", photo: "/directors/phillips.jpg" },
    creator: { id: 8, name: "Todd Phillips" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    trailer: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
    videoUrl: { uz: "/videos/joker-uz.mp4", ru: "/videos/joker-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 9, slug: "avengers-endgame",
    translations: {
      uz: { title: "Qasoskorlar: Final", description: "Superqahramonlar yakuniy jangda." },
      ru: { title: "Мстители: Финал", description: "Финальная битва супергероев." },
    },
    originalTitle: "Avengers: Endgame", year: 2019, duration: 181, rating: 8.4, quality: "HD", ageLimit: 13,
    genres: ["Action", "Adventure"], actors: [],
    director: { id: 9, name: "Russo Brothers", photo: "/directors/russo.jpg" },
    creator: { id: 9, name: "Russo Brothers" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    trailer: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    videoUrl: { uz: "/videos/endgame-uz.mp4", ru: "/videos/endgame-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 10, slug: "titanic",
    translations: {
      uz: { title: "Titanik", description: "Muhabbat va fojiya hikoyasi." },
      ru: { title: "Титаник", description: "История любви и трагедии." },
    },
    originalTitle: "Titanic", year: 1997, duration: 195, rating: 7.9, quality: "HD", ageLimit: 13,
    genres: ["Drama", "Romance"], actors: [],
    director: { id: 10, name: "James Cameron", photo: "/directors/cameron.jpg" },
    creator: { id: 10, name: "James Cameron" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kHXEpqv5HD8o7JnNKILtRJZkBFm.jpg",
    trailer: "https://www.youtube.com/watch?v=2e-eXJ6HgkQ",
    videoUrl: { uz: "/videos/titanic-uz.mp4", ru: "/videos/titanic-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 11, slug: "fight-club",
    translations: {
      uz: { title: "Fight Club", description: "Yashirin klub haqida." },
      ru: { title: "Бойцовский клуб", description: "История тайного клуба." },
    },
    originalTitle: "Fight Club", year: 1999, duration: 139, rating: 8.8, quality: "HD", ageLimit: 18,
    genres: ["Drama"], actors: [],
    director: { id: 11, name: "David Fincher", photo: "/directors/fincher.jpg" },
    creator: { id: 11, name: "David Fincher" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzVysXn.jpg",
    trailer: "https://www.youtube.com/watch?v=SUXWAEX2jlg",
    videoUrl: { uz: "/videos/fightclub-uz.mp4", ru: "/videos/fightclub-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 12, slug: "forrest-gump",
    translations: {
      uz: { title: "Forrest Gump", description: "Oddiy inson hayoti." },
      ru: { title: "Форрест Гамп", description: "История жизни простого человека." },
    },
    originalTitle: "Forrest Gump", year: 1994, duration: 142, rating: 8.8, quality: "HD", ageLimit: 13,
    genres: ["Drama"], actors: [],
    director: { id: 12, name: "Robert Zemeckis", photo: "/directors/zemeckis.jpg" },
    creator: { id: 12, name: "Robert Zemeckis" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/qdIMHd4sEfJSckfVJfKQvisL02a.jpg",
    trailer: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    videoUrl: { uz: "/videos/forrest-uz.mp4", ru: "/videos/forrest-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 13, slug: "shawshank-redemption",
    translations: {
      uz: { title: "Shoushenkdan qochish", description: "Qamoqxona hikoyasi." },
      ru: { title: "Побег из Шоушенка", description: "История побега из тюрьмы." },
    },
    originalTitle: "The Shawshank Redemption", year: 1994, duration: 142, rating: 9.3, quality: "HD", ageLimit: 13,
    genres: ["Drama"], actors: [],
    director: { id: 13, name: "Frank Darabont", photo: "/directors/darabont.jpg" },
    creator: { id: 13, name: "Frank Darabont" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    trailer: "https://www.youtube.com/watch?v=NmzuHjWmXOc",
    videoUrl: { uz: "/videos/shawshank-uz.mp4", ru: "/videos/shawshank-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 14, slug: "spider-man-no-way-home",
    translations: {
      uz: { title: "O'rgimchak odam: Uyga yo'l yo'q", description: "Multiverse hikoyasi." },
      ru: { title: "Человек-паук: Нет пути домой", description: "История мультивселенной." },
    },
    originalTitle: "Spider-Man: No Way Home", year: 2021, duration: 148, rating: 8.2, quality: "HD", ageLimit: 13,
    genres: ["Action", "Adventure"], actors: [],
    director: { id: 14, name: "Jon Watts", photo: "/directors/watts.jpg" },
    creator: { id: 14, name: "Jon Watts" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    trailer: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    videoUrl: { uz: "/videos/spiderman-uz.mp4", ru: "/videos/spiderman-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 15, slug: "the-lord-of-the-rings",
    translations: {
      uz: { title: "Uzuklar hukmdori", description: "Fantastik sarguzasht." },
      ru: { title: "Властелин колец", description: "Фэнтези приключение." },
    },
    originalTitle: "The Lord of the Rings: The Fellowship of the Ring", year: 2001, duration: 178, rating: 8.8, quality: "HD", ageLimit: 13,
    genres: ["Fantasy", "Adventure"], actors: [],
    director: { id: 15, name: "Peter Jackson", photo: "/directors/jackson.jpg" },
    creator: { id: 15, name: "Peter Jackson" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/pIgHoFNdnmRFxGhYMaDBpEBXEPt.jpg",
    trailer: "https://www.youtube.com/watch?v=V75dMMIW2B4",
    videoUrl: { uz: "/videos/lotr-uz.mp4", ru: "/videos/lotr-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 16, slug: "mad-max-fury-road",
    translations: {
      uz: { title: "Mad Max: G'azab yo'li", description: "Postapokaliptik jang va quvish sahnalari." },
      ru: { title: "Безумный Макс: Дорога ярости", description: "Постапокалиптический боевик." },
    },
    originalTitle: "Mad Max: Fury Road", year: 2015, duration: 120, rating: 8.1, quality: "HD", ageLimit: 16,
    genres: ["action", "adventure", "sci-fi", "thriller"], actors: [],
    director: { id: 16, name: "George Miller", photo: "/directors/miller.jpg" },
    creator: { id: 16, name: "George Miller" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg",
    trailer: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
    videoUrl: { uz: "/videos/madmax-uz.mp4", ru: "/videos/madmax-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 17, slug: "toy-story",
    translations: {
      uz: { title: "Toy Story", description: "O'yinchoqlar hayoti haqida animatsion film." },
      ru: { title: "История игрушек", description: "Анимационный фильм о жизни игрушек." },
    },
    originalTitle: "Toy Story", year: 1995, duration: 81, rating: 8.3, quality: "HD", ageLimit: 0,
    genres: ["animation", "family", "comedy"], actors: [],
    director: { id: 17, name: "John Lasseter", photo: "/directors/lasseter.jpg" },
    creator: { id: 17, name: "John Lasseter" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPl9KcertX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/dji4Fm0gCDVb9DQQMRvAI8YNnTz.jpg",
    trailer: "https://www.youtube.com/watch?v=KYz2wyBy3kc",
    videoUrl: { uz: "/videos/toystory-uz.mp4", ru: "/videos/toystory-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 18, slug: "the-conjuring",
    translations: {
      uz: { title: "The Conjuring", description: "Qo'rqinchli paranormal voqealar." },
      ru: { title: "Заклятие", description: "Фильм ужасов о паранормальных явлениях." },
    },
    originalTitle: "The Conjuring", year: 2013, duration: 112, rating: 7.5, quality: "HD", ageLimit: 18,
    genres: ["horror", "thriller", "mystery"], actors: [],
    director: { id: 18, name: "James Wan", photo: "/directors/wan.jpg" },
    creator: { id: 18, name: "James Wan" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/ounAMHzHFkHznWVYMnfbWmxFDQY.jpg",
    trailer: "https://www.youtube.com/watch?v=k10ETZ41q5o",
    videoUrl: { uz: "/videos/conjuring-uz.mp4", ru: "/videos/conjuring-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 19, slug: "the-godfather",
    translations: {
      uz: { title: "Cho'qintirgan ota", description: "Mafiya oilasi haqida jinoyat dramasi." },
      ru: { title: "Крестный отец", description: "Криминальная драма о мафиозной семье." },
    },
    originalTitle: "The Godfather", year: 1972, duration: 175, rating: 9.2, quality: "HD", ageLimit: 16,
    genres: ["crime", "drama"], actors: [],
    director: { id: 19, name: "Francis Ford Coppola", photo: "/directors/coppola.jpg" },
    creator: { id: 19, name: "Francis Ford Coppola" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsLegHnDmni5.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    trailer: "https://www.youtube.com/watch?v=sY1S34973zA",
    videoUrl: { uz: "/videos/godfather-uz.mp4", ru: "/videos/godfather-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 20, slug: "la-la-land",
    translations: {
      uz: { title: "La La Land", description: "Musiqali romantik drama." },
      ru: { title: "Ла-Ла Ленд", description: "Музыкальная романтическая драма." },
    },
    originalTitle: "La La Land", year: 2016, duration: 128, rating: 8.0, quality: "HD", ageLimit: 13,
    genres: ["romance", "drama", "music"], actors: [],
    director: { id: 20, name: "Damien Chazelle", photo: "/directors/chazelle.jpg" },
    creator: { id: 20, name: "Damien Chazelle" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/nadTnfQQJSAqmMFBGnpL0lbXNNI.jpg",
    trailer: "https://www.youtube.com/watch?v=0pdqf4P9MB8",
    videoUrl: { uz: "/videos/lalaland-uz.mp4", ru: "/videos/lalaland-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 21, slug: "saving-private-ryan",
    translations: {
      uz: { title: "Xususiy Rayanni qutqarish", description: "Urush dramasi." },
      ru: { title: "Спасти рядового Райана", description: "Военная драма." },
    },
    originalTitle: "Saving Private Ryan", year: 1998, duration: 169, rating: 8.6, quality: "HD", ageLimit: 16,
    genres: ["war", "drama", "history"], actors: [],
    director: { id: 21, name: "Steven Spielberg", photo: "/directors/spielberg.jpg" },
    creator: { id: 21, name: "Steven Spielberg" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/zm0nSQQbjmNzjDFAiqRthmUfzFe.jpg",
    trailer: "https://www.youtube.com/watch?v=9CiW_DgxCnQ",
    videoUrl: { uz: "/videos/ryan-uz.mp4", ru: "/videos/ryan-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 22, slug: "django-unchained",
    translations: {
      uz: { title: "Django", description: "Western janridagi jangovar film." },
      ru: { title: "Джанго освобожденный", description: "Вестерн боевик." },
    },
    originalTitle: "Django Unchained", year: 2012, duration: 165, rating: 8.4, quality: "HD", ageLimit: 18,
    genres: ["western", "drama", "action"], actors: [],
    director: { id: 22, name: "Quentin Tarantino", photo: "/directors/tarantino.jpg" },
    creator: { id: 22, name: "Quentin Tarantino" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/5WJnDCRTe3lAfMOyS5Q4jNSGHfB.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg",
    trailer: "https://www.youtube.com/watch?v=eUdM9vrCbow",
    videoUrl: { uz: "/videos/django-uz.mp4", ru: "/videos/django-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 23, slug: "planet-earth",
    translations: {
      uz: { title: "Planet Earth", description: "Tabiat haqidagi hujjatli film." },
      ru: { title: "Планета Земля", description: "Документальный фильм о природе." },
    },
    originalTitle: "Planet Earth", year: 2006, duration: 550, rating: 9.4, quality: "HD", ageLimit: 0,
    genres: ["documentary"], actors: [],
    director: { id: 23, name: "Alastair Fothergill", photo: "/directors/fothergill.jpg" },
    creator: { id: 23, name: "BBC" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/lMoEXFtQ4oKVem9wGGBrUUSCYkK.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/9Q7HRfnFKDRm5tBMFhsEkCeWDsF.jpg",
    trailer: "https://www.youtube.com/watch?v=GoV0KoMg0HI",
    videoUrl: { uz: "/videos/planet-uz.mp4", ru: "/videos/planet-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 24, slug: "knives-out",
    translations: {
      uz: { title: "Knives Out", description: "Sirli jinoyat tergovi." },
      ru: { title: "Достать ножи", description: "Детективная история." },
    },
    originalTitle: "Knives Out", year: 2019, duration: 130, rating: 7.9, quality: "HD", ageLimit: 13,
    genres: ["mystery", "crime", "comedy"], actors: [],
    director: { id: 24, name: "Rian Johnson", photo: "/directors/johnson.jpg" },
    creator: { id: 24, name: "Rian Johnson" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/pThyQovXQrws2vTZRaqFBXFcALZ.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg",
    trailer: "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
    videoUrl: { uz: "/videos/knives-uz.mp4", ru: "/videos/knives-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 25, slug: "hocus-pocus",
    translations: {
      uz: { title: "Hocus Pocus", description: "Oilaviy fantaziya filmi." },
      ru: { title: "Фокус-покус", description: "Семейная фантазия." },
    },
    originalTitle: "Hocus Pocus", year: 1993, duration: 96, rating: 6.9, quality: "HD", ageLimit: 7,
    genres: ["family", "fantasy", "comedy", "tv-movie"], actors: [],
    director: { id: 25, name: "Kenny Ortega", photo: "/directors/ortega.jpg" },
    creator: { id: 25, name: "Kenny Ortega" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/4GE3hMWfRQ2xsBrUzf1ctJxaEqX.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/2Dc4YQSoFwIjvBBfXb2H8TtWnC4.jpg",
    trailer: "https://www.youtube.com/watch?v=zy-MVMKQ-Bc",
    videoUrl: { uz: "/videos/hocus-uz.mp4", ru: "/videos/hocus-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },

  // ══ YANGI 5 TA ══

  {
    id: 26, slug: "parasite",
    translations: {
      uz: { title: "Parazit", description: "Kambag'al oila boy xonadonga asta-sekin kirib boradi — va hammasi nazoratdan chiqadi." },
      ru: { title: "Паразиты", description: "Бедная семья постепенно проникает в жизнь богатой — и всё выходит из-под контроля." },
    },
    originalTitle: "Parasite", year: 2019, duration: 132, rating: 8.5, quality: "HD", ageLimit: 16,
    genres: ["Drama", "Thriller", "Crime"], actors: [],
    director: { id: 26, name: "Bong Joon-ho", photo: "/directors/bong.jpg" },
    creator: { id: 26, name: "Bong Joon-ho" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
    trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    videoUrl: { uz: "/videos/parasite-uz.mp4", ru: "/videos/parasite-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 27, slug: "whiplash",
    translations: {
      uz: { title: "Qamchi zarba", description: "Yosh barabanchi shafqatsiz o'qituvchi qo'lida mukammallikka intiladi." },
      ru: { title: "Одержимость", description: "Молодой барабанщик стремится к совершенству под руководством жёсткого наставника." },
    },
    originalTitle: "Whiplash", year: 2014, duration: 107, rating: 8.5, quality: "HD", ageLimit: 16,
    genres: ["Drama", "Music"],
    actors: [
      { id: 30, name: "Miles Teller", role: "Andrew", photo: "/actors/teller.jpg" },
      { id: 31, name: "J.K. Simmons", role: "Fletcher", photo: "/actors/simmons.jpg" },
    ],
    director: { id: 27, name: "Damien Chazelle", photo: "/directors/chazelle.jpg" },
    creator: { id: 27, name: "Damien Chazelle" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/6bbZ6XyvgfjhQwbplnUh1LSj1ky.jpg",
    trailer: "https://www.youtube.com/watch?v=7d_jQycdQGo",
    videoUrl: { uz: "/videos/whiplash-uz.mp4", ru: "/videos/whiplash-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 28, slug: "silence-of-the-lambs",
    translations: {
      uz: { title: "Qo'zilarning jimjitligi", description: "Yosh FBI agenti serial qotilni tutish uchun qamoqdagi psixopatdan yordam so'raydi." },
      ru: { title: "Молчание ягнят", description: "Молодой агент ФБР обращается за помощью к заключённому психопату для поимки серийного убийцы." },
    },
    originalTitle: "The Silence of the Lambs", year: 1991, duration: 118, rating: 8.6, quality: "HD", ageLimit: 18,
    genres: ["Thriller", "Crime", "Drama"], actors: [],
    director: { id: 28, name: "Jonathan Demme", photo: "/directors/demme.jpg" },
    creator: { id: 28, name: "Jonathan Demme" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/mfwq2nMBmAT7GShSFkoTAuMhCGV.jpg",
    trailer: "https://www.youtube.com/watch?v=W6Mm8Sbe__o",
    videoUrl: { uz: "/videos/lambs-uz.mp4", ru: "/videos/lambs-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
  {
    id: 29, slug: "spirited-away",
    translations: {
      uz: { title: "Ruhlar dunyosida", description: "10 yoshli Chihiro ruhlar dunyosiga tushib qoladi va ota-onasini qutqarishi kerak." },
      ru: { title: "Унесённые призраками", description: "10-летняя Тихиро попадает в мир духов и должна спасти своих родителей." },
    },
    originalTitle: "Spirited Away", year: 2001, duration: 125, rating: 8.6, quality: "HD", ageLimit: 7,
    genres: ["animation", "fantasy", "adventure"], actors: [],
    director: { id: 29, name: "Hayao Miyazaki", photo: "/directors/miyazaki.jpg" },
    creator: { id: 29, name: "Studio Ghibli" },
    availableLanguages: ["uz", "ru"], defaultAudio: "uz",
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg",
    trailer: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
    videoUrl: { uz: "/videos/spirited-uz.mp4", ru: "/videos/spirited-ru.mp4" },
    isPremium: false, createdAt: "2026-02-28",
  },
  {
    id: 30, slug: "goodfellas",
    translations: {
      uz: { title: "Yaxshi yigitlar", description: "Real voqealarga asoslangan — italyan mafiyasiga a'zo bo'lgan Henry Hill hayoti." },
      ru: { title: "Славные парни", description: "Основано на реальных событиях — жизнь Генри Хилла в итальянской мафии." },
    },
    originalTitle: "Goodfellas", year: 1990, duration: 146, rating: 8.7, quality: "HD", ageLimit: 18,
    genres: ["Crime", "Drama"], actors: [],
    director: { id: 30, name: "Martin Scorsese", photo: "/directors/scorsese.jpg" },
    creator: { id: 30, name: "Martin Scorsese" },
    availableLanguages: ["uz", "ru"], defaultAudio: "ru",
    poster: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
    backdrop: "https://image.tmdb.org/t/p/original/sw7mordbZxgITU877yTpZCud90M.jpg",
    trailer: "https://www.youtube.com/watch?v=qo5jJpHtI1Y",
    videoUrl: { uz: "/videos/goodfellas-uz.mp4", ru: "/videos/goodfellas-ru.mp4" },
    isPremium: true, createdAt: "2026-02-28",
  },
];